name: Build

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Build with PyInstaller
        if: runner.os != 'Windows'
        run: uv run pyinstaller -F --add-data "app-window.slint:." main.py

      - name: Build with PyInstaller
        if: runner.os == 'Windows'
        run: uv run pyinstaller -F --add-data "app-window.slint;." main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ runner.os }}
          path: dist/
